FORMAT: 1A

# BeersAPI

Beers is a simple API allowing consumers to view beers and vote on them to choose their favorite.

## Beers Collection [/beers]

### List All Beers [GET]

+ Response 200 (application/json)

        [
            {
                "brewery": "Happy Brewer",
                "brewType": "IPA",
                "ABV": 5.0,
                "IBU": 30,
                "Region": "Northeast",
                "Tax": 10.4,
                "ExportControl": "ATF"
            },
            {
                "brewery": "More Happy Brewer",
                "brewType": "Wheat",
                "ABV": 4.6,
                "IBU": 15,
                "Region": "Northwest",
                "Tax": 10.35
                "ExportControl": "ATF"
            }            
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }